// [BUTTON/IMAGE + RECGAME] + [SAVESTATES + FORCE320x256] + TOTALROMS
	LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
		LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
		LAYOUT_SpaceOuter,  TRUE,

// BUTTON/IMAGE + RECGAME
		LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
			LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
			LAYOUT_SpaceOuter,  TRUE,
			//LAYOUT_SpaceInner,  FALSE,
// BUTTON/IMAGE
			LAYOUT_AddChild, IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
				//LAYOUT_Orientation,    LAYOUT_ORIENT_VERT,
				//LAYOUT_HorizAlignment, LALIGN_CENTER,
				//LAYOUT_SpaceOuter,     FALSE,
				//LAYOUT_SpaceInner,     FALSE,
				LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, //"space.gadget",
					SPACE_MinWidth, 20,
				TAG_DONE),
				LAYOUT_AddChild, OBJ(OID_PREVIEW_BTN) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
					GA_ID,         OID_PREVIEW_BTN,
					GA_RelVerify,  TRUE,
					GA_Underscore, 0,
					//GA_Text,       "RUN GAME",
					GA_HintInfo,   GetString(&li, OID_PREVIEW_BTN_HELP),
					BUTTON_BevelStyle,  BVS_THIN,
					//BUTTON_Transparent, TRUE,
					//BUTTON_BackgroundPen, BLOCKPEN,
					//BUTTON_FillPen,       BLOCKPEN,
					BUTTON_RenderImage, OBJ(OID_PREVIEW_IMG) = IIntuition->NewObject(BitMapClass, NULL, //"bitmap.image",
						//IA_Scalable, TRUE,
						BITMAP_Screen, dgg->screen,
						//BITMAP_Masking, TRUE,
					TAG_DONE),
				TAG_DONE),
				CHILD_MaxWidth, 256+2,  // pixels width of preview + button border
				CHILD_MinWidth, 256+2,  // pixels width of preview + button border
				CHILD_MaxHeight, 224+2, // pixels height of preview + button border
				CHILD_MinHeight, 224+2, // pixels height of preview + button border
				LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, //"space.gadget",
					SPACE_MinWidth, 20,
				TAG_DONE),
			TAG_DONE), // END of BUTTON/IMAGE
// RECGAME
			LAYOUT_AddChild, OBJ(OID_GAME_OPTIONS) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
				GA_ID,         OID_GAME_OPTIONS,
				GA_RelVerify,  TRUE,
				GA_Underscore, 0,
				GA_HintInfo,   GetString(&li, MSG_GUI_GAME_OPTIONS_HELP),
				CHOOSER_Labels,   dgg->game_opts_list,
				CHOOSER_Selected, 0,
			TAG_DONE),
		TAG_DONE), // END of BUTTON/IMAGE + RECGAME
		CHILD_WeightedHeight, 0,

		LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, //"space.gadget",
			SPACE_MinHeight, 10,
		TAG_DONE),

// SAVESTATES + FORCE320x256
		LAYOUT_AddChild, /*OBJ(OID_OPTIONS_GROUP) =*/ IIntuition->NewObject(LayoutClass, NULL, //"layout.gadget",
			LAYOUT_Orientation, LAYOUT_ORIENT_VERT,
			LAYOUT_SpaceOuter,  TRUE,
			//LAYOUT_SpaceInner,  FALSE,
			LAYOUT_BevelStyle,  BVS_GROUP,
			LAYOUT_AddChild, OBJ(OID_SAVESTATES) = IIntuition->NewObject(ChooserClass, NULL, //"chooser.gadget",
				GA_ID,         OID_SAVESTATES,
				GA_RelVerify,  TRUE,
				GA_Underscore, 0,
				GA_HintInfo,   GetString(&li, MSG_GUI_SAVESTATES_HELP),
				CHOOSER_Labels,   dgg->savestates_list,
				CHOOSER_Selected, 0,
			TAG_DONE),
			CHILD_WeightedWidth, 0,
			CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
				LABEL_Text, GetString(&li, MSG_GUI_SAVESTATES),//"Load savestate",
			TAG_DONE),
			LAYOUT_AddChild, OBJ(OID_FORCELOWRES) = IIntuition->NewObject(ChooserClass, NULL,
				//GA_ID,         OID_FORCELOWRES,
				//GA_RelVerify,  TRUE,
				GA_Underscore, 0,
				GA_HintInfo,   GetString(&li, MSG_GUI_FORCELOWRES_HELP),
				CHOOSER_LabelArray, lowres_array,
				CHOOSER_Selected,   dgg->myTT.force_lowres,
			TAG_DONE),
			CHILD_WeightedWidth, 0,
			CHILD_Label, IIntuition->NewObject(LabelClass, NULL,// "label.image",
				LABEL_Text, GetString(&li, MSG_GUI_FORCELOWRES),
			TAG_DONE),
/*
			LAYOUT_AddChild, OBJ(OID_FORCELOWRES) = IIntuition->NewObject(CheckBoxClass, NULL, //"chooser.gadget",
				GA_ID,         OID_FORCELOWRES,
				GA_RelVerify,  TRUE,
				GA_Underscore, 0,
				GA_Text,       GetString(&li, MSG_GUI_FORCELOWRES),
				GA_HintInfo,   GetString(&li, MSG_GUI_FORCELOWRES_HELP),
				GA_Selected,   dgg->myTT.force_lowres,
				//CHECKBOX_TextPlace, PLACETEXT_LEFT,
				TAG_DONE),
				//CHILD_WeightedWidth, 0,
*/
			TAG_DONE), // END of SAVESTATES + FORCE320x256

			LAYOUT_AddChild, IIntuition->NewObject(SpaceClass, NULL, //"space.gadget",
				SPACE_MinHeight, 10,
			TAG_DONE),

// TOTALROMS
			LAYOUT_AddChild, OBJ(OID_TOTALROMS) = IIntuition->NewObject(ButtonClass, NULL, //"button.gadget",
				//GA_ID,         OID_TOTALROMS,
				//GA_RelVerify,  TRUE,
				GA_ReadOnly,   TRUE,
				GA_Underscore, 0,
				GA_Text,       GetString(&li, MSG_GUI_TOTALROMS),
				BUTTON_Justification, BCJ_LEFT,
				BUTTON_BevelStyle,    BVS_NONE,
				BUTTON_Transparent,   TRUE,
			TAG_DONE),
			//CHILD_WeightedWidth,  0,
			CHILD_WeightedHeight, 0,

		TAG_DONE), // END of [BUTTON/IMAGE + RECGAME] + [SAVESTATES + FORCE320x256] + TOTALROMS
		CHILD_WeightedWidth, 35,
